name: Publish blog and game to Github pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: env GOOS=js GOARCH=wasm go build -o dist/uboot.wasm cmd/main.go
      - run: cp -r static/. dist
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./blog"
          destination: "./dist/blog"
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy pages
        uses: actions/deploy-pages@v4
        id: deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}