name: Publish blog and game to Github pages
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: env GOOS=js GOARCH=wasm go build -o dist/uboot.wasm cmd/main.go
      - run: cp -r static/. dist
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./blog"
          destination: "./dist/blog"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}